# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131GK_-TTxAgtYzRDEq4aRjld8B0ZY1g2
"""

import requests
import datetime
import firebase_admin
from firebase_admin import credentials, firestore

if not firebase_admin._apps:
    cred = credentials.Certificate("firebase-key.json")
    firebase_admin.initialize_app(cred)

db = firestore.client()

# Crops list
crops = ["cotton", "sugar", "maize", "rice", "edible-oil", "pulses", "spices", "wheat"]

def fetch_and_store():
    today = datetime.date.today().isoformat()

    for crop in crops:
        try:
            url = f"https://agriinfo.co/api/{crop}"
            response = requests.get(url)
            response.raise_for_status()
            data = response.json()

            if not data:
                print(f"⚠️ No data found for {crop}")
                continue

            for item in data:
                doc_id = f"{crop}_{today}_{item.get('province_name', 'unknown')}"
                db.collection("market_prices").document(doc_id).set({
                    "date": today,
                    "crop": item.get("by_product_name_en", item.get("by_product_name", crop.capitalize())),
                    "province": item.get("province_name", "Unknown"),
                    "avg_minimum": float(item.get("avg_minimum", 0)),
                    "avg_maximum": float(item.get("avg_maximum", 0)),
                    "average": float(item.get("average", 0)),
                    "unit": item.get("unit", "N/A")
                })
            print(f"✅ {crop} data stored for {today}")
        except Exception as e:
            print(f"❌ Error fetching/storing {crop}: {e}")

fetch_and_store()